name: Fetch Xinference Tags

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests mysql-connector-python

      - name: Fetch and compare Xinference tags
        id: fetch-tags
        run: |
          python scripts/fetch_xinference_tags.py
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Trigger Docker Image Sync workflow
        if: steps.fetch-tags.outputs.has_new_images == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          event-type: sync-images
          client-payload: '{"message": "New Xinference image detected"}'
